### ISSUE TITLE
Node: Implement the secure built-in wallet

### ISSUE THREAD

**Issue by alexeykiselev** [wavesplatform/gowaves#209]
**Аbstract**

Implement the secure, detachable wallet that will be used by node during new blocks generation.

**Motivation and Purposes**

To enable block generation on node we need a built-in wallet that holds private keys that can be used by miner for block generation.  The wallet should have a storage in form of encrypted file. 

**Specification**

 * Wallet's file format is JSON encrypted with AES.
 * Key generation algorithm like [Argon2](https://en.wikipedia.org/wiki/Argon2) should be used to create AES encryption key from passphrase.
 * Node should have an API method to Open/Decrypt wallet with a passphrase. This API method should be accessible only by local endpoint. 
 * Node should provide an API method to Close/Detach a wallet that should unload and wipe out from memory the containing private keys. 
 * Wallet should be able to store multiple accounts derived from different seed phrases/account seed. 
 * User should be able to created wallet's file using special utility that should accept/generate seed phrases, account seeds or private keys in different formats. 
 * Private keys inside a walled should be identified by its account. 

**Examples and Implementation**
Ergo has a detachable wallet that could be created, opened and closed using it's API.

**Comment by mhtafsir** [comment]
Love
