### ISSUE TITLE
[BUG] Executing Node binary on test- or stagenet causes an error.

### ISSUE THREAD

**Issue by suadhasani** [wavesplatform/gowaves#249]
**Describe the bug**
Executing Node binary on test- or stagenet causes an error.

**To Reproduce**
1. Download 0.3.0 "Node Alpha"
2. `./node -blockchain-type testnet`
3. See error

**Error Message**
`ERROR	failed to open genesis file: open /Users/alexeykiselev/go/src/github.com/wavesplatform/gowaves/pkg/state/genesis/stagenet.json: no such file or directory`

**Comment by alexeykiselev** [comment]
Thank you for reporting a bug!
But this issue was fixed by https://github.com/wavesplatform/gowaves/pull/223. 
The current master is the best choice to run the gowaves node.
