### ISSUE TITLE
[FEATURE] Why to run this, I need to download and store blockchain again???

### ISSUE THREAD

**Issue by username1565** [wavesplatform/gowaves#285]
**Аbstract**
>Is your feature request related to a problem? Please describe.

Yes. Blockchain too large.

**Motivation and Purposes**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [I need to download large files and lost the limited traffic].

** Specification**
>A clear and concise description of what you want to happen. Describe alternatives you've considered

I just don't see the option to import the existing blockchain, or read the data inside the blocks from the already runned node. Why I need to download the binary file, to import this, when I already have synchronized blockchain???

**Backwards Compatibility**
>Can your proposition affect any existing features?

I think, WMD can loading the blocks from the runned node, by requests on the NODE REST API,
or read the `.ldb`-files in the existing directory of the node, without downloading and store again the binary-file, with full blockchain (33GB).

**Examples and Implementation**
>Examples of implementation in other projects?

https://github.com/PyWaves/WavesDataFeed make the requests on the runned node, to parse data inside the blocks, which are existing there.

**Comment by alexeykiselev** [comment]
The only way to synchronise WMD to a Waves node is using node's **gRPC API**. The support of REST API was dropped because gRPC is faster. The import of blockchain file can be used to speed up initial synchronisation. By the way, WavesDataFeed lacks this functionality. 

Usually, WMD should be run with the command:
```
wmd -db [path to WMD data folder] -symbols [path to symbols.txt] -node [URL of gRPC API]
```

For example, on our test server WND starts as follows:
```
wmd -db /var/lib/wmd/ -address 0.0.0.0:6990 -node mainnet-aws-fr-1.wavesnodes.com:6871 -symbols /usr/share/wmd/symbols.txt -sync-interval 1 -matcher 9cpfKN9suPNvfeUNphzxXMjcnn974eme8ZhWUjaktzU5
```

**Comment by alexeykiselev** [comment]
Import of blockchain file is optional. It can be used to build initial state of WMD using command:
```
wmd -db [path to WMD data folder] -symbols [path to symbols.txt] -import-file [path to blockchain *.dms file]
```
Importing of blockchain file can save a lot of time. 
After completion of the process, the blockchain file can be deleted and the `-import-file` option not required any more:
```
wmd -db [path to WMD data folder] -symbols [path to symbols.txt] -node [URL of gRPC API]
```

**Comment by username1565** [comment]
Hello, alexeykiselev!
I just [download here](https://github.com/wavesplatform/gowaves/releases/tag/v0.3.0)
[wmd_v0.3.0_Windows-64bit.zip](https://github.com/wavesplatform/gowaves/releases/download/v0.3.0/wmd_v0.3.0_Windows-64bit.zip)
then, download [symbols.txt, here](https://raw.githubusercontent.com/wavesplatform/gowaves/master/cmd/wmd/symbols.txt) by saving this by right click, in browser.
After this all, I put symbols.txt, near wmd.exe, which was been unpacked from that .zip-file,
then, I just created the folder "data", to store database there,
and then, I created the following `start_WMD.bat`:
```
start_WMD.bat
[disk:]
cd "disk:\folder_where_wmd.exe_contains\"
wmd -db /data/ -address 0.0.0.0:6990 -node mainnet-aws-fr-1.wavesnodes.com:6871 -symbols symbols.txt -sync-interval 1 -matcher 9cpfKN9suPNvfeUNphzxXMjcnn974eme8ZhWUjaktzU5
pause
```

After running `start_WMD.bat` by double-click,
I see some synchrnorization, but I don't see any files in "data"-folder...
How to specify the correct relative or full pathway for `data`-directory, on Windows?
Also, I did try to close this program, and run again. I see, the synchronization beginning from the end, where previous blocks was been already downloaded.
This means, wmd.exe, store the data somewhere... Where??? I don't want to download 33 GB again... Hm... But... If this really needed to working WMD, I want to know, how to specify the specified folder to store this all non-actual data.

**Comment by username1565** [comment]
One more question... Is this possible, to load trading history and candles [from the node v0.5.0](https://github.com/wavesplatform/gowaves/releases/tag/v0.5.0)??
I just don't see WMD v0.5.0 there, in the attached files...

**Comment by alexeykiselev** [comment]
I think the problem is in leading forward slash in `/data/`. Better to put full path here, for example `C:\WMD\data`.

> So, I think, will be better to synchronize the candles from .ldb-files

The main reason it won't work is that the access to .ldb files is exclusive, only one process can use them at a time. So, the node should be down then WMD reading them. By the way, internal structure of node's storage is constantly changes, so it will be hard to support those changes. 

The REST API was dropped because it is not supported by gowaves node, but the gRPC API is.

Please, refer to [**'Installation via ZIP file'** section of documentation](https://docs.wavesplatform.com/en/waves-node/extensions/grpc-server/)  to install gRPC server add-on or create a bug report at [Waves Issues](https://github.com/wavesplatform/Waves/issues).

> And I see, wmd_v0.2.0_Windows-64bit.zip try to do some GET-requests, on the node,
but this is processed over TCP, not over HTTP.
HTTP works over TCP, so it's OK. But the old version doesn't support new features of the node, so at some block the synchronisation will be broken.

**Comment by alexeykiselev** [comment]
It is possible to use gowaves node as a data source for WMD. But, actually, we haven't tested it yet because we are trying hard to catch up with main functionality of the node. 
Any help with this will be very appreciated. 

The latest version of WMD is compatible only with new pre-released versions of Waves node 1.2.x, that's why we decided not to put it in the latest release.

**Comment by username1565** [comment]
@alexeykiselev, 
>I think the problem is in leading forward slash in /data/. Better to put full path here, for example C:\WMD\data
Yeap, this working, without any single and double quotes. I just unlock wmd.exe in firewall and antivirus, and then I see the files in `data`-folder. Before unlock this, wmd.exe was been locked by Comodo Firewall, and synchronization was been processed, but no any files in folder. So I was been confused with this. xD

>The main reason it won't work is that the access to .ldb files is exclusive, only one process can use them at a time.
>So, the node should be down then WMD reading them. 
> By the way, internal structure of node's storage is constantly changes, so it will be hard to support those changes.
OK.

>The REST API was dropped because it is not supported by gowaves node, but the gRPC API is.
I just try to download [wmd_v0.2.0_Windows-64bit.zip](https://github.com/wavesplatform/gowaves/releases/download/v0.2.0/wmd_v0.2.0_Windows-64bit.zip),
and then, I go here: https://dev.pywaves.org/nodes/, find the one node with "Free sockets",
and run wmd.exe with this node at port 6869. Synchronization is processing sucessfully!
So, I have one more question... Is how is possible to run the node with enabled this "Free sockets"?
I don't see any instructions in the node config-file to enable this sockets.
And I opened this issue: https://github.com/wavesplatform/Waves/issues/3048

After all, I just found this text:
>WebSocket proxy on TCP port 6991

here: https://github.com/PyWaves/WavesDataFeed
And I don't understand what to do now, to enable this "Free sockets".

I want to make wmd.exe working with my node, through TCP (because wmd.exe try to connect there over TCP), so need to enable "Free sockets" (or Websockets) on the node...
Will be better to send this GET-requests on the local node over HTTP, at port 6869,
while this local node is running, to update candles, and trade history locally, not from remote server,
which can be go offline at any time...
Maybe, you can investigate this, and fix this in next releases, because I don't understand anything in GoLang-files, and just using pre-compiled binaries.

>Please, refer to 'Installation via ZIP file' section of documentation
There is no any zip-files. So I used .tgz -files, and got throw exception, after try to run the node with gRPC extensions.

>HTTP works over TCP, so it's OK.
>But the old version doesn't support new features of the node,
>so at some block the synchronisation will be broken.
Hm... But... Why I cann't load some data from my local node over HTTP by requests at port 6869,
but I can load this from node, with enabled "Free sockets", by requests on port 6869 there?
Maybe, you can see the source code, and maybe something need to fix in the source code?
Just I don't know...

**Comment by alexeykiselev** [comment]
I see a little misunderstanding here. 

Free sockets at https://dev.pywaves.org/nodes/ means that a node has an available network "slots" for connections from other nodes. PyWaves service tries to establish connection to nodes network port and marks it with "yes" if succeeded. Node tries to use all available connection "slots" constantly trying to establish new connections, that's why there is so few of "yes" in the list. 

But the WebSocket API of https://github.com/PyWaves/WavesDataFeed is completely different [thing](https://en.wikipedia.org/wiki/WebSocket). It's a special API that sends constant stream of data updates from the service to a connected browser (or other client). But this WebSocket API was so resource-hungry that it was always switched off on our public servers. 

WMD doesn't support WebSocket API.

**Comment by username1565** [comment]
Yeap. I just did try to open swagger at port 6869 on the nodes from this list: https://dev.pywaves.org/nodes/
and don't get success for any node, where p2p-port is opened.
This is because 6868 port is opened, but NODE REST API not enabled here, or port is not opened.
I did try to open swagger on 6869 port for IP-addresses where "Free sockets" is enabled...
And I got success there, by this IP addresses.

I see, the synchronization is processed from NODE REST API:
```
wmd -db disk:\fullpath\data\ -address 0.0.0.0:6990 -node 127.0.0.1:6869 -symbols symbols.txt -sync-interval 1 -matcher 9cpfKN9suPNvfeUNphzxXMjcnn974eme8ZhWUjaktzU5
```
and this is working with local node for wmd.exe v0.2.0.

But this not working for WMD v1.0.3,
and as I understand from previous answers, synchronization of wmd.exe v0.2.0 will stop at some block... Hm...
I just try to synchronize. I see data folder have size lesser than 200 MB at block 1000000, so no problem to store this.

**Comment by username1565** [comment]
wmd.exe v0.2.0.
Synchronization from NODE REST API on local node, at port 6869 was been stopped.
Maybe, you can fix it.

wmd console.log:
```
2020-04-10T10:19:53.150+0300    INFO    Synchronizing 401157 blocks starting fro
m height 1610030
2020-04-10T10:19:53.251+0300    ERROR   Failed to apply blocks: unknown transact
ion type 16 version 1
2020-04-10T10:19:53.252+0300    INFO    Local height 1610029, node height 201118
6
2020-04-10T10:19:53.262+0300    INFO    Synchronizing 401157 blocks starting fro
m height 1610030
2020-04-10T10:19:53.272+0300    ERROR   Failed to apply blocks: unknown transact
ion type 16 version 1
2020-04-10T10:19:54.157+0300    INFO    Local height 1610029, node height 201118
6
2020-04-10T10:19:54.166+0300    INFO    Synchronizing 401157 blocks starting fro
m height 1610030
2020-04-10T10:19:54.175+0300    ERROR   Failed to apply blocks: unknown transact
ion type 16 version 1
2020-04-10T10:19:55.155+0300    INFO    Local height 1610029, node height 201118
6
2020-04-10T10:19:55.165+0300    INFO    Synchronizing 401157 blocks starting fro
m height 1610030
2020-04-10T10:19:55.175+0300    ERROR   Failed to apply blocks: unknown transact
ion type 16 version 1
2020-04-10T10:19:56.157+0300    INFO    Local height 1610029, node height 201118
6
... and repeat it again and again...
```

node console.log:
```
2020-04-10 10:18:58,169 INFO  [tor.default-dispatcher-15] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/at/1610030
2020-04-10 10:18:59,164 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/height
2020-04-10 10:18:59,165 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/805015
2020-04-10 10:18:59,166 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1207522
2020-04-10 10:18:59,167 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1408776
2020-04-10 10:18:59,167 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1509403
2020-04-10 10:18:59,167 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1559716
2020-04-10 10:18:59,168 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1584873
2020-04-10 10:18:59,168 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1597451
2020-04-10 10:18:59,168 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1603740
2020-04-10 10:18:59,169 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1606885
2020-04-10 10:18:59,169 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1608457
2020-04-10 10:18:59,170 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609243
2020-04-10 10:18:59,171 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609636
2020-04-10 10:18:59,171 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609833
2020-04-10 10:18:59,172 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609931
2020-04-10 10:18:59,172 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609980
2020-04-10 10:18:59,173 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610005
2020-04-10 10:18:59,173 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610017
2020-04-10 10:18:59,174 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610023
2020-04-10 10:18:59,174 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610026
2020-04-10 10:18:59,175 INFO  [tor.default-dispatcher-15] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610028
2020-04-10 10:18:59,175 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610029
2020-04-10 10:18:59,177 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/at/1610030
2020-04-10 10:19:00,158 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/height
2020-04-10 10:19:00,159 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/805015
2020-04-10 10:19:00,159 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1207522
2020-04-10 10:19:00,160 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1408776
2020-04-10 10:19:00,160 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1509403
2020-04-10 10:19:00,161 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1559716
2020-04-10 10:19:00,161 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1584873
2020-04-10 10:19:00,161 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1597451
2020-04-10 10:19:00,162 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1603740
2020-04-10 10:19:00,163 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1606885
2020-04-10 10:19:00,163 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1608457
2020-04-10 10:19:00,164 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609243
2020-04-10 10:19:00,164 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609636
2020-04-10 10:19:00,165 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609833
2020-04-10 10:19:00,165 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609931
2020-04-10 10:19:00,165 INFO  [tor.default-dispatcher-16] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1609980
2020-04-10 10:19:00,166 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610005
2020-04-10 10:19:00,167 INFO  [tor.default-dispatcher-15] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610017
2020-04-10 10:19:00,168 INFO  [tor.default-dispatcher-15] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610023
2020-04-10 10:19:00,168 INFO  [tor.default-dispatcher-13] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610026
2020-04-10 10:19:00,168 INFO  [tor.default-dispatcher-13] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610028
2020-04-10 10:19:00,169 INFO  [tor.default-dispatcher-27] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/headers/at/1610029
2020-04-10 10:19:00,170 INFO  [tor.default-dispatcher-15] c.w.a.h.CompositeHttpS
ervice - HTTP 200 OK from GET http://127.0.0.1:6869/blocks/at/1610030
... and repeat this again and again...
```

**Comment by username1565** [comment]
wmd.exe v0.3.0 stop synchronization at blocks `1610029-1610030` from gRPC-server `mainnet-aws-fr-1.wavesnodes.com:6871` too.
