### ISSUE TITLE
[V1.2] Update node's gRPC API

### ISSUE THREAD

**Issue by alexeykiselev** [wavesplatform/gowaves#290]
** Specification**
Node's gRPC API should be updated to [version 1.2.4 of waves/protobuf-schemas](https://github.com/wavesplatform/protobuf-schemas/commit/27ca1cbf6b38da63981365ab55a615b8fa1c73f5).

- [x] Add transaction to InvokeScriptResult
- [x] Add ApplicationStatus
- [x] Add total block ID to MicroBlockMessage

**Comment by zer0main** [comment]
Done in https://github.com/wavesplatform/gowaves/pull/296
