### ISSUE TITLE
[FEATURE] Add support of block range requests to WMD

### ISSUE THREAD

**Issue by alexeykiselev** [wavesplatform/gowaves#370]
**Аbstract**
Now WMD requests blocks one-by-one using `waves.node.grpc.BlocksApi/GetBlock` method, in cases then it's clear that WMD have to request range of blocks better use `waves.node.grpc.BlocksApi/GetBlockRange` gRPC API method. 

**Motivation and Purposes**
This part is legacy of old HTTP API, we have to use all advantages of gRPC API.

**Comment by esuwu** [comment]
done
