### ISSUE TITLE
[BUG] go build error

### ISSUE THREAD

**Issue by zhp1254** [wavesplatform/gowaves#395]
github.com/wavesplatform/gowaves/pkg/crypto/internal/groth16/bls12381
..\..\github.com\wavesplatform\gowaves\pkg\crypto\internal\groth16\bls12381\verifier.go:16:94: cannot use inputs[i] (type *big.Int) as type *bls123
81.Fr in argument to PointG1.MulScalar

**Comment by alexeykiselev** [comment]
Hello, 
what is your build environment and what command do you use?

**Comment by esuwu** [comment]
@zhp1254 could you please describe how you use verifier? Are you trying to build the node or you use this code as lib for some kind of your implementation?
