### ISSUE TITLE
[BUG] Excessive error logging

### ISSUE THREAD

**Issue by deemru** [wavesplatform/gowaves#404]
Current version (v0.8.5) logs these messages as errors:
- `transaction with id %s exists`
- `first block %s exists`
- `micro reference not found`
- `BlocksApplier: failed get parent height, firstBlock id %s, for firstBlock %s`

But they are definitely not errors an user should even know about.

**Comment by esuwu** [comment]
https://github.com/wavesplatform/gowaves/pull/433
