### ISSUE TITLE
connect public node error

### ISSUE THREAD

**Issue by zychappy** [wavesplatform/gowaves#67]
```
c,err:=NewClient()
	require.NoError(t, err)
	block,_,err:=c.Blocks.Last(context.Background())
	require.NoError(t, err)

```
Error:      	Received unexpected 
        	            	failed to decode Attachment from JSON Value: zero length string

**Comment by alexeykiselev** [comment]
Fixed with https://github.com/wavesplatform/gowaves/pull/68#pullrequestreview-190709265
Thank you for report!
