### ISSUE TITLE
How to GenerateKeyPair if I have only seed

### ISSUE THREAD

**Issue by voronindev** [wavesplatform/gowaves#87]
How should I receive SecretKey & PublicKey, if i have a seed? I'm using the following function:
`sk, pk := crypto.GenerateKeyPair([]byte("gospel rule red grit faculty clog happy client concert final weird plastic"))`

But sk and pk are not as expected. How can I receive correct sk and pk in this way?

**Comment by alexeykiselev** [comment]
You are almost correct. The only thing you forgot is to create an account seed. 

Basically, the key pair created like this: 
1. You have to generate a seed phrase and convert it into a slice of bytes.
2. To create an account seed, you have to prepend the seed with 4 bytes of the sequential number of an account generated from the seed. 
3. Take a `SecureHash` digest from the account seed bytes.
4. Use the digest to generate a key pair.

Here the code:

```golang
func GenerateKeyPair(seed string, n int) {
	s := []byte(seed)
	iv := make([]byte, 4)
	binary.BigEndian.PutUint32(iv, uint32(n))
	s = append(iv, s...)
	accSeed, err := crypto.SecureHash(s)
	if err != nil {
		fmt.Println(err)
	}
	sk, pk := crypto.GenerateKeyPair(accSeed[:])
	fmt.Println("SK:", sk.String())
	fmt.Println("PK:", pk.String())
	a, err := proto.NewAddressFromPublicKey('W', pk) // W for the MainNet
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("ADDR:", a.String())
}
```

This code for your seed and n = 0 gives:
```
SK: 8ZRgjq6t9HcrNw8wECBJZ79gySCmisDYNUShtFMAVscE
PK: 4i54XfBJpYwGt1pbxUtvQ4UxhYyTiNXFcvQmuY3YUQf7
ADDR: 3P9yNac633QTRJBhzs3yHzXgETP2xY3uZpi
```
Is it what your expect?

**Comment by voronindev** [comment]
Thanks a lot!
